/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.x.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
)

// checks if the PostAccessListCreateRequestItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostAccessListCreateRequestItemsInner{}

// PostAccessListCreateRequestItemsInner struct for PostAccessListCreateRequestItemsInner
type PostAccessListCreateRequestItemsInner struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewPostAccessListCreateRequestItemsInner instantiates a new PostAccessListCreateRequestItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAccessListCreateRequestItemsInner() *PostAccessListCreateRequestItemsInner {
	this := PostAccessListCreateRequestItemsInner{}
	return &this
}

// NewPostAccessListCreateRequestItemsInnerWithDefaults instantiates a new PostAccessListCreateRequestItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAccessListCreateRequestItemsInnerWithDefaults() *PostAccessListCreateRequestItemsInner {
	this := PostAccessListCreateRequestItemsInner{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PostAccessListCreateRequestItemsInner) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAccessListCreateRequestItemsInner) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PostAccessListCreateRequestItemsInner) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PostAccessListCreateRequestItemsInner) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *PostAccessListCreateRequestItemsInner) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAccessListCreateRequestItemsInner) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *PostAccessListCreateRequestItemsInner) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *PostAccessListCreateRequestItemsInner) SetPassword(v string) {
	o.Password = &v
}

func (o PostAccessListCreateRequestItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostAccessListCreateRequestItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullablePostAccessListCreateRequestItemsInner struct {
	value *PostAccessListCreateRequestItemsInner
	isSet bool
}

func (v NullablePostAccessListCreateRequestItemsInner) Get() *PostAccessListCreateRequestItemsInner {
	return v.value
}

func (v *NullablePostAccessListCreateRequestItemsInner) Set(val *PostAccessListCreateRequestItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAccessListCreateRequestItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAccessListCreateRequestItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAccessListCreateRequestItemsInner(val *PostAccessListCreateRequestItemsInner) *NullablePostAccessListCreateRequestItemsInner {
	return &NullablePostAccessListCreateRequestItemsInner{value: val, isSet: true}
}

func (v NullablePostAccessListCreateRequestItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAccessListCreateRequestItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


