/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.x.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"time"
)

// checks if the TokenRefreshResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRefreshResponse{}

// TokenRefreshResponse struct for TokenRefreshResponse
type TokenRefreshResponse struct {
	// JWT
	Token *string `json:"token,omitempty"`
	// Token expiry time
	Expires *time.Time `json:"expires,omitempty"`
	// Scope of the Token, defaults to 'user'
	Scope *string `json:"scope,omitempty"`
}

// NewTokenRefreshResponse instantiates a new TokenRefreshResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRefreshResponse() *TokenRefreshResponse {
	this := TokenRefreshResponse{}
	return &this
}

// NewTokenRefreshResponseWithDefaults instantiates a new TokenRefreshResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRefreshResponseWithDefaults() *TokenRefreshResponse {
	this := TokenRefreshResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *TokenRefreshResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenRefreshResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *TokenRefreshResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *TokenRefreshResponse) SetToken(v string) {
	o.Token = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *TokenRefreshResponse) GetExpires() time.Time {
	if o == nil || IsNil(o.Expires) {
		var ret time.Time
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenRefreshResponse) GetExpiresOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *TokenRefreshResponse) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given time.Time and assigns it to the Expires field.
func (o *TokenRefreshResponse) SetExpires(v time.Time) {
	o.Expires = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *TokenRefreshResponse) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenRefreshResponse) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *TokenRefreshResponse) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *TokenRefreshResponse) SetScope(v string) {
	o.Scope = &v
}

func (o TokenRefreshResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRefreshResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Expires) {
		toSerialize["expires"] = o.Expires
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

type NullableTokenRefreshResponse struct {
	value *TokenRefreshResponse
	isSet bool
}

func (v NullableTokenRefreshResponse) Get() *TokenRefreshResponse {
	return v.value
}

func (v *NullableTokenRefreshResponse) Set(val *TokenRefreshResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRefreshResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRefreshResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRefreshResponse(val *TokenRefreshResponse) *NullableTokenRefreshResponse {
	return &NullableTokenRefreshResponse{value: val, isSet: true}
}

func (v NullableTokenRefreshResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRefreshResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


