/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.13.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetUserUserIDParameter - struct for GetUserUserIDParameter
type GetUserUserIDParameter struct {
	Int64 *int64
	String *string
}

// int64AsGetUserUserIDParameter is a convenience function that returns int64 wrapped in GetUserUserIDParameter
func Int64AsGetUserUserIDParameter(v *int64) GetUserUserIDParameter {
	return GetUserUserIDParameter{
		Int64: v,
	}
}

// stringAsGetUserUserIDParameter is a convenience function that returns string wrapped in GetUserUserIDParameter
func StringAsGetUserUserIDParameter(v *string) GetUserUserIDParameter {
	return GetUserUserIDParameter{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetUserUserIDParameter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int64
	err = newStrictDecoder(data).Decode(&dst.Int64)
	if err == nil {
		jsonInt64, _ := json.Marshal(dst.Int64)
		if string(jsonInt64) == "{}" { // empty struct
			dst.Int64 = nil
		} else {
			if err = validator.Validate(dst.Int64); err != nil {
				dst.Int64 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int64 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int64 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetUserUserIDParameter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetUserUserIDParameter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetUserUserIDParameter) MarshalJSON() ([]byte, error) {
	if src.Int64 != nil {
		return json.Marshal(&src.Int64)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetUserUserIDParameter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Int64 != nil {
		return obj.Int64
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetUserUserIDParameter) GetActualInstanceValue() (interface{}) {
	if obj.Int64 != nil {
		return *obj.Int64
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetUserUserIDParameter struct {
	value *GetUserUserIDParameter
	isSet bool
}

func (v NullableGetUserUserIDParameter) Get() *GetUserUserIDParameter {
	return v.value
}

func (v *NullableGetUserUserIDParameter) Set(val *GetUserUserIDParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserUserIDParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserUserIDParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserUserIDParameter(val *GetUserUserIDParameter) *NullableGetUserUserIDParameter {
	return &NullableGetUserUserIDParameter{value: val, isSet: true}
}

func (v NullableGetUserUserIDParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserUserIDParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


