/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.12.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)


// GetSettings200ResponseInnerValue Value in almost any form
type GetSettings200ResponseInnerValue struct {
	ArrayOfAny *[]interface{}
	Float32 *float32
	Int64 *int64
	MapmapOfStringAny *map[string]interface{}
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetSettings200ResponseInnerValue) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfAny
	err = json.Unmarshal(data, &dst.ArrayOfAny);
	if err == nil {
		jsonArrayOfAny, _ := json.Marshal(dst.ArrayOfAny)
		if string(jsonArrayOfAny) == "{}" { // empty struct
			dst.ArrayOfAny = nil
		} else {
			return nil // data stored in dst.ArrayOfAny, return on the first match
		}
	} else {
		dst.ArrayOfAny = nil
	}

	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32);
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into Int64
	err = json.Unmarshal(data, &dst.Int64);
	if err == nil {
		jsonInt64, _ := json.Marshal(dst.Int64)
		if string(jsonInt64) == "{}" { // empty struct
			dst.Int64 = nil
		} else {
			return nil // data stored in dst.Int64, return on the first match
		}
	} else {
		dst.Int64 = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetSettings200ResponseInnerValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetSettings200ResponseInnerValue) MarshalJSON() ([]byte, error) {
	if src.ArrayOfAny != nil {
		return json.Marshal(&src.ArrayOfAny)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.Int64 != nil {
		return json.Marshal(&src.Int64)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetSettings200ResponseInnerValue struct {
	value *GetSettings200ResponseInnerValue
	isSet bool
}

func (v NullableGetSettings200ResponseInnerValue) Get() *GetSettings200ResponseInnerValue {
	return v.value
}

func (v *NullableGetSettings200ResponseInnerValue) Set(val *GetSettings200ResponseInnerValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSettings200ResponseInnerValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSettings200ResponseInnerValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSettings200ResponseInnerValue(val *GetSettings200ResponseInnerValue) *NullableGetSettings200ResponseInnerValue {
	return &NullableGetSettings200ResponseInnerValue{value: val, isSet: true}
}

func (v NullableGetSettings200ResponseInnerValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSettings200ResponseInnerValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


