/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.13.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the GetProxyHosts200ResponseInnerCertificate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProxyHosts200ResponseInnerCertificate{}

// GetProxyHosts200ResponseInnerCertificate Certificate object
type GetProxyHosts200ResponseInnerCertificate struct {
	// Unique identifier
	Id int64 `json:"id"`
	// Date and time of creation
	CreatedOn string `json:"created_on"`
	// Date and time of last update
	ModifiedOn string `json:"modified_on"`
	// User ID
	OwnerUserId int64 `json:"owner_user_id"`
	Provider string `json:"provider" validate:"regexp=^(letsencrypt|other)$"`
	// Nice Name for the custom certificate
	NiceName string `json:"nice_name"`
	// Domain Names separated by a comma
	DomainNames []string `json:"domain_names"`
	// Date and time of expiration
	ExpiresOn string `json:"expires_on"`
	Owner *GetAuditLogs200ResponseInnerUser `json:"owner,omitempty"`
	Meta GetCertificates200ResponseInnerMeta `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _GetProxyHosts200ResponseInnerCertificate GetProxyHosts200ResponseInnerCertificate

// NewGetProxyHosts200ResponseInnerCertificate instantiates a new GetProxyHosts200ResponseInnerCertificate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProxyHosts200ResponseInnerCertificate(id int64, createdOn string, modifiedOn string, ownerUserId int64, provider string, niceName string, domainNames []string, expiresOn string, meta GetCertificates200ResponseInnerMeta) *GetProxyHosts200ResponseInnerCertificate {
	this := GetProxyHosts200ResponseInnerCertificate{}
	this.Id = id
	this.CreatedOn = createdOn
	this.ModifiedOn = modifiedOn
	this.OwnerUserId = ownerUserId
	this.Provider = provider
	this.NiceName = niceName
	this.DomainNames = domainNames
	this.ExpiresOn = expiresOn
	this.Meta = meta
	return &this
}

// NewGetProxyHosts200ResponseInnerCertificateWithDefaults instantiates a new GetProxyHosts200ResponseInnerCertificate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProxyHosts200ResponseInnerCertificateWithDefaults() *GetProxyHosts200ResponseInnerCertificate {
	this := GetProxyHosts200ResponseInnerCertificate{}
	return &this
}

// GetId returns the Id field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetId(v int64) {
	o.Id = v
}

// GetCreatedOn returns the CreatedOn field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetCreatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetCreatedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedOn, true
}

// SetCreatedOn sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetCreatedOn(v string) {
	o.CreatedOn = v
}

// GetModifiedOn returns the ModifiedOn field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetModifiedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedOn
}

// GetModifiedOnOk returns a tuple with the ModifiedOn field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetModifiedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedOn, true
}

// SetModifiedOn sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetModifiedOn(v string) {
	o.ModifiedOn = v
}

// GetOwnerUserId returns the OwnerUserId field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetOwnerUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetOwnerUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerUserId, true
}

// SetOwnerUserId sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetOwnerUserId(v int64) {
	o.OwnerUserId = v
}

// GetProvider returns the Provider field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetProvider(v string) {
	o.Provider = v
}

// GetNiceName returns the NiceName field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetNiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NiceName
}

// GetNiceNameOk returns a tuple with the NiceName field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetNiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NiceName, true
}

// SetNiceName sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetNiceName(v string) {
	o.NiceName = v
}

// GetDomainNames returns the DomainNames field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetDomainNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DomainNames
}

// GetDomainNamesOk returns a tuple with the DomainNames field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetDomainNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DomainNames, true
}

// SetDomainNames sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetDomainNames(v []string) {
	o.DomainNames = v
}

// GetExpiresOn returns the ExpiresOn field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetExpiresOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresOn
}

// GetExpiresOnOk returns a tuple with the ExpiresOn field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetExpiresOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresOn, true
}

// SetExpiresOn sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetExpiresOn(v string) {
	o.ExpiresOn = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *GetProxyHosts200ResponseInnerCertificate) GetOwner() GetAuditLogs200ResponseInnerUser {
	if o == nil || IsNil(o.Owner) {
		var ret GetAuditLogs200ResponseInnerUser
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetOwnerOk() (*GetAuditLogs200ResponseInnerUser, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given GetAuditLogs200ResponseInnerUser and assigns it to the Owner field.
func (o *GetProxyHosts200ResponseInnerCertificate) SetOwner(v GetAuditLogs200ResponseInnerUser) {
	o.Owner = &v
}

// GetMeta returns the Meta field value
func (o *GetProxyHosts200ResponseInnerCertificate) GetMeta() GetCertificates200ResponseInnerMeta {
	if o == nil {
		var ret GetCertificates200ResponseInnerMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetProxyHosts200ResponseInnerCertificate) GetMetaOk() (*GetCertificates200ResponseInnerMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *GetProxyHosts200ResponseInnerCertificate) SetMeta(v GetCertificates200ResponseInnerMeta) {
	o.Meta = v
}

func (o GetProxyHosts200ResponseInnerCertificate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProxyHosts200ResponseInnerCertificate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_on"] = o.CreatedOn
	toSerialize["modified_on"] = o.ModifiedOn
	toSerialize["owner_user_id"] = o.OwnerUserId
	toSerialize["provider"] = o.Provider
	toSerialize["nice_name"] = o.NiceName
	toSerialize["domain_names"] = o.DomainNames
	toSerialize["expires_on"] = o.ExpiresOn
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProxyHosts200ResponseInnerCertificate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_on",
		"modified_on",
		"owner_user_id",
		"provider",
		"nice_name",
		"domain_names",
		"expires_on",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetProxyHosts200ResponseInnerCertificate := _GetProxyHosts200ResponseInnerCertificate{}

	err = json.Unmarshal(data, &varGetProxyHosts200ResponseInnerCertificate)

	if err != nil {
		return err
	}

	*o = GetProxyHosts200ResponseInnerCertificate(varGetProxyHosts200ResponseInnerCertificate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_on")
		delete(additionalProperties, "modified_on")
		delete(additionalProperties, "owner_user_id")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "nice_name")
		delete(additionalProperties, "domain_names")
		delete(additionalProperties, "expires_on")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProxyHosts200ResponseInnerCertificate struct {
	value *GetProxyHosts200ResponseInnerCertificate
	isSet bool
}

func (v NullableGetProxyHosts200ResponseInnerCertificate) Get() *GetProxyHosts200ResponseInnerCertificate {
	return v.value
}

func (v *NullableGetProxyHosts200ResponseInnerCertificate) Set(val *GetProxyHosts200ResponseInnerCertificate) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProxyHosts200ResponseInnerCertificate) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProxyHosts200ResponseInnerCertificate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProxyHosts200ResponseInnerCertificate(val *GetProxyHosts200ResponseInnerCertificate) *NullableGetProxyHosts200ResponseInnerCertificate {
	return &NullableGetProxyHosts200ResponseInnerCertificate{value: val, isSet: true}
}

func (v NullableGetProxyHosts200ResponseInnerCertificate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProxyHosts200ResponseInnerCertificate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


