/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.12.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the GetAccessLists200ResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccessLists200ResponseItemsInner{}

// GetAccessLists200ResponseItemsInner struct for GetAccessLists200ResponseItemsInner
type GetAccessLists200ResponseItemsInner struct {
	// Unique identifier
	Id int64 `json:"id"`
	// Date and time of creation
	CreatedOn string `json:"created_on"`
	// Date and time of last update
	ModifiedOn string `json:"modified_on"`
	// Access List ID
	AccessListId int64 `json:"access_list_id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Hint string `json:"hint"`
	Meta map[string]interface{} `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _GetAccessLists200ResponseItemsInner GetAccessLists200ResponseItemsInner

// NewGetAccessLists200ResponseItemsInner instantiates a new GetAccessLists200ResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccessLists200ResponseItemsInner(id int64, createdOn string, modifiedOn string, accessListId int64, username string, password string, hint string, meta map[string]interface{}) *GetAccessLists200ResponseItemsInner {
	this := GetAccessLists200ResponseItemsInner{}
	this.Id = id
	this.CreatedOn = createdOn
	this.ModifiedOn = modifiedOn
	this.AccessListId = accessListId
	this.Username = username
	this.Password = password
	this.Hint = hint
	this.Meta = meta
	return &this
}

// NewGetAccessLists200ResponseItemsInnerWithDefaults instantiates a new GetAccessLists200ResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccessLists200ResponseItemsInnerWithDefaults() *GetAccessLists200ResponseItemsInner {
	this := GetAccessLists200ResponseItemsInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetAccessLists200ResponseItemsInner) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetAccessLists200ResponseItemsInner) SetId(v int64) {
	o.Id = v
}

// GetCreatedOn returns the CreatedOn field value
func (o *GetAccessLists200ResponseItemsInner) GetCreatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetCreatedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedOn, true
}

// SetCreatedOn sets field value
func (o *GetAccessLists200ResponseItemsInner) SetCreatedOn(v string) {
	o.CreatedOn = v
}

// GetModifiedOn returns the ModifiedOn field value
func (o *GetAccessLists200ResponseItemsInner) GetModifiedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedOn
}

// GetModifiedOnOk returns a tuple with the ModifiedOn field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetModifiedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedOn, true
}

// SetModifiedOn sets field value
func (o *GetAccessLists200ResponseItemsInner) SetModifiedOn(v string) {
	o.ModifiedOn = v
}

// GetAccessListId returns the AccessListId field value
func (o *GetAccessLists200ResponseItemsInner) GetAccessListId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccessListId
}

// GetAccessListIdOk returns a tuple with the AccessListId field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetAccessListIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessListId, true
}

// SetAccessListId sets field value
func (o *GetAccessLists200ResponseItemsInner) SetAccessListId(v int64) {
	o.AccessListId = v
}

// GetUsername returns the Username field value
func (o *GetAccessLists200ResponseItemsInner) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *GetAccessLists200ResponseItemsInner) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *GetAccessLists200ResponseItemsInner) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *GetAccessLists200ResponseItemsInner) SetPassword(v string) {
	o.Password = v
}

// GetHint returns the Hint field value
func (o *GetAccessLists200ResponseItemsInner) GetHint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hint
}

// GetHintOk returns a tuple with the Hint field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetHintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hint, true
}

// SetHint sets field value
func (o *GetAccessLists200ResponseItemsInner) SetHint(v string) {
	o.Hint = v
}

// GetMeta returns the Meta field value
func (o *GetAccessLists200ResponseItemsInner) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetAccessLists200ResponseItemsInner) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetAccessLists200ResponseItemsInner) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetAccessLists200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccessLists200ResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_on"] = o.CreatedOn
	toSerialize["modified_on"] = o.ModifiedOn
	toSerialize["access_list_id"] = o.AccessListId
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	toSerialize["hint"] = o.Hint
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAccessLists200ResponseItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_on",
		"modified_on",
		"access_list_id",
		"username",
		"password",
		"hint",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAccessLists200ResponseItemsInner := _GetAccessLists200ResponseItemsInner{}

	err = json.Unmarshal(data, &varGetAccessLists200ResponseItemsInner)

	if err != nil {
		return err
	}

	*o = GetAccessLists200ResponseItemsInner(varGetAccessLists200ResponseItemsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_on")
		delete(additionalProperties, "modified_on")
		delete(additionalProperties, "access_list_id")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "hint")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAccessLists200ResponseItemsInner struct {
	value *GetAccessLists200ResponseItemsInner
	isSet bool
}

func (v NullableGetAccessLists200ResponseItemsInner) Get() *GetAccessLists200ResponseItemsInner {
	return v.value
}

func (v *NullableGetAccessLists200ResponseItemsInner) Set(val *GetAccessLists200ResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccessLists200ResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccessLists200ResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccessLists200ResponseItemsInner(val *GetAccessLists200ResponseItemsInner) *NullableGetAccessLists200ResponseItemsInner {
	return &NullableGetAccessLists200ResponseItemsInner{value: val, isSet: true}
}

func (v NullableGetAccessLists200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccessLists200ResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


