/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.12.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetProxyHosts200ResponseInnerAccessList - struct for GetProxyHosts200ResponseInnerAccessList
type GetProxyHosts200ResponseInnerAccessList struct {
	CreateAccessList201Response *CreateAccessList201Response
}

// CreateAccessList201ResponseAsGetProxyHosts200ResponseInnerAccessList is a convenience function that returns CreateAccessList201Response wrapped in GetProxyHosts200ResponseInnerAccessList
func CreateAccessList201ResponseAsGetProxyHosts200ResponseInnerAccessList(v *CreateAccessList201Response) GetProxyHosts200ResponseInnerAccessList {
	return GetProxyHosts200ResponseInnerAccessList{
		CreateAccessList201Response: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetProxyHosts200ResponseInnerAccessList) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into CreateAccessList201Response
	err = newStrictDecoder(data).Decode(&dst.CreateAccessList201Response)
	if err == nil {
		jsonCreateAccessList201Response, _ := json.Marshal(dst.CreateAccessList201Response)
		if string(jsonCreateAccessList201Response) == "{}" { // empty struct
			dst.CreateAccessList201Response = nil
		} else {
			if err = validator.Validate(dst.CreateAccessList201Response); err != nil {
				dst.CreateAccessList201Response = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateAccessList201Response = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateAccessList201Response = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetProxyHosts200ResponseInnerAccessList)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetProxyHosts200ResponseInnerAccessList)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetProxyHosts200ResponseInnerAccessList) MarshalJSON() ([]byte, error) {
	if src.CreateAccessList201Response != nil {
		return json.Marshal(&src.CreateAccessList201Response)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetProxyHosts200ResponseInnerAccessList) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateAccessList201Response != nil {
		return obj.CreateAccessList201Response
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetProxyHosts200ResponseInnerAccessList) GetActualInstanceValue() (interface{}) {
	if obj.CreateAccessList201Response != nil {
		return *obj.CreateAccessList201Response
	}

	// all schemas are nil
	return nil
}

type NullableGetProxyHosts200ResponseInnerAccessList struct {
	value *GetProxyHosts200ResponseInnerAccessList
	isSet bool
}

func (v NullableGetProxyHosts200ResponseInnerAccessList) Get() *GetProxyHosts200ResponseInnerAccessList {
	return v.value
}

func (v *NullableGetProxyHosts200ResponseInnerAccessList) Set(val *GetProxyHosts200ResponseInnerAccessList) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProxyHosts200ResponseInnerAccessList) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProxyHosts200ResponseInnerAccessList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProxyHosts200ResponseInnerAccessList(val *GetProxyHosts200ResponseInnerAccessList) *NullableGetProxyHosts200ResponseInnerAccessList {
	return &NullableGetProxyHosts200ResponseInnerAccessList{value: val, isSet: true}
}

func (v NullableGetProxyHosts200ResponseInnerAccessList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProxyHosts200ResponseInnerAccessList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


