/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.x.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// PutProxyHostUpdateRequestCertificateId Certificate ID
type PutProxyHostUpdateRequestCertificateId struct {
	Int64 *int64
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PutProxyHostUpdateRequestCertificateId) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Int64
	err = json.Unmarshal(data, &dst.Int64);
	if err == nil {
		jsonInt64, _ := json.Marshal(dst.Int64)
		if string(jsonInt64) == "{}" { // empty struct
			dst.Int64 = nil
		} else {
			return nil // data stored in dst.Int64, return on the first match
		}
	} else {
		dst.Int64 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PutProxyHostUpdateRequestCertificateId)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *PutProxyHostUpdateRequestCertificateId) MarshalJSON() ([]byte, error) {
	if src.Int64 != nil {
		return json.Marshal(&src.Int64)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullablePutProxyHostUpdateRequestCertificateId struct {
	value *PutProxyHostUpdateRequestCertificateId
	isSet bool
}

func (v NullablePutProxyHostUpdateRequestCertificateId) Get() *PutProxyHostUpdateRequestCertificateId {
	return v.value
}

func (v *NullablePutProxyHostUpdateRequestCertificateId) Set(val *PutProxyHostUpdateRequestCertificateId) {
	v.value = val
	v.isSet = true
}

func (v NullablePutProxyHostUpdateRequestCertificateId) IsSet() bool {
	return v.isSet
}

func (v *NullablePutProxyHostUpdateRequestCertificateId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutProxyHostUpdateRequestCertificateId(val *PutProxyHostUpdateRequestCertificateId) *NullablePutProxyHostUpdateRequestCertificateId {
	return &NullablePutProxyHostUpdateRequestCertificateId{value: val, isSet: true}
}

func (v NullablePutProxyHostUpdateRequestCertificateId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutProxyHostUpdateRequestCertificateId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


