/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.13.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the LoginAsUser200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginAsUser200Response{}

// LoginAsUser200Response Login object
type LoginAsUser200Response struct {
	// JWT Token
	Token string `json:"token"`
	// Token Expiry Timestamp
	Expires string `json:"expires"`
	User GetAuditLogs200ResponseInnerUser `json:"user"`
	AdditionalProperties map[string]interface{}
}

type _LoginAsUser200Response LoginAsUser200Response

// NewLoginAsUser200Response instantiates a new LoginAsUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginAsUser200Response(token string, expires string, user GetAuditLogs200ResponseInnerUser) *LoginAsUser200Response {
	this := LoginAsUser200Response{}
	this.Token = token
	this.Expires = expires
	this.User = user
	return &this
}

// NewLoginAsUser200ResponseWithDefaults instantiates a new LoginAsUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginAsUser200ResponseWithDefaults() *LoginAsUser200Response {
	this := LoginAsUser200Response{}
	return &this
}

// GetToken returns the Token field value
func (o *LoginAsUser200Response) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *LoginAsUser200Response) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *LoginAsUser200Response) SetToken(v string) {
	o.Token = v
}

// GetExpires returns the Expires field value
func (o *LoginAsUser200Response) GetExpires() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value
// and a boolean to check if the value has been set.
func (o *LoginAsUser200Response) GetExpiresOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expires, true
}

// SetExpires sets field value
func (o *LoginAsUser200Response) SetExpires(v string) {
	o.Expires = v
}

// GetUser returns the User field value
func (o *LoginAsUser200Response) GetUser() GetAuditLogs200ResponseInnerUser {
	if o == nil {
		var ret GetAuditLogs200ResponseInnerUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *LoginAsUser200Response) GetUserOk() (*GetAuditLogs200ResponseInnerUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *LoginAsUser200Response) SetUser(v GetAuditLogs200ResponseInnerUser) {
	o.User = v
}

func (o LoginAsUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginAsUser200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["expires"] = o.Expires
	toSerialize["user"] = o.User

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoginAsUser200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"expires",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginAsUser200Response := _LoginAsUser200Response{}

	err = json.Unmarshal(data, &varLoginAsUser200Response)

	if err != nil {
		return err
	}

	*o = LoginAsUser200Response(varLoginAsUser200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "token")
		delete(additionalProperties, "expires")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoginAsUser200Response struct {
	value *LoginAsUser200Response
	isSet bool
}

func (v NullableLoginAsUser200Response) Get() *LoginAsUser200Response {
	return v.value
}

func (v *NullableLoginAsUser200Response) Set(val *LoginAsUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginAsUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginAsUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginAsUser200Response(val *LoginAsUser200Response) *NullableLoginAsUser200Response {
	return &NullableLoginAsUser200Response{value: val, isSet: true}
}

func (v NullableLoginAsUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginAsUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


