/*
Nginx Proxy Manager API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.x.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
)

// checks if the PutProxyHostUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutProxyHostUpdateRequest{}

// PutProxyHostUpdateRequest struct for PutProxyHostUpdateRequest
type PutProxyHostUpdateRequest struct {
	// Domain Names separated by a comma
	DomainNames []string `json:"domain_names,omitempty"`
	ForwardScheme *string `json:"forward_scheme,omitempty"`
	ForwardHost *string `json:"forward_host,omitempty"`
	ForwardPort *int64 `json:"forward_port,omitempty"`
	CertificateId *PutProxyHostUpdateRequestCertificateId `json:"certificate_id,omitempty"`
	// Is SSL Forced
	SslForced *boolAsInt `json:"ssl_forced,omitempty"`
	// Is HSTS Enabled
	HstsEnabled *boolAsInt `json:"hsts_enabled,omitempty"`
	// Is HSTS Enabled
	HstsSubdomains *boolAsInt `json:"hsts_subdomains,omitempty"`
	// HTTP2 Protocol Support
	Http2Support *boolAsInt `json:"http2_support,omitempty"`
	// Should we block common exploits
	BlockExploits *boolAsInt `json:"block_exploits,omitempty"`
	// Should we cache assets
	CachingEnabled *boolAsInt `json:"caching_enabled,omitempty"`
	// Allow Websocket Upgrade for all paths
	AllowWebsocketUpgrade *boolAsInt `json:"allow_websocket_upgrade,omitempty"`
	// Access List ID
	AccessListId *int64 `json:"access_list_id,omitempty"`
	AdvancedConfig *string `json:"advanced_config,omitempty"`
	// Is Enabled
	Enabled *boolAsInt `json:"enabled,omitempty"`
	Meta map[string]interface{} `json:"meta,omitempty"`
	Locations []PutProxyHostUpdateRequestLocationsInner `json:"locations,omitempty"`
}

// NewPutProxyHostUpdateRequest instantiates a new PutProxyHostUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutProxyHostUpdateRequest() *PutProxyHostUpdateRequest {
	this := PutProxyHostUpdateRequest{}
	return &this
}

// NewPutProxyHostUpdateRequestWithDefaults instantiates a new PutProxyHostUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutProxyHostUpdateRequestWithDefaults() *PutProxyHostUpdateRequest {
	this := PutProxyHostUpdateRequest{}
	return &this
}

// GetDomainNames returns the DomainNames field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetDomainNames() []string {
	if o == nil || IsNil(o.DomainNames) {
		var ret []string
		return ret
	}
	return o.DomainNames
}

// GetDomainNamesOk returns a tuple with the DomainNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetDomainNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.DomainNames) {
		return nil, false
	}
	return o.DomainNames, true
}

// HasDomainNames returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasDomainNames() bool {
	if o != nil && !IsNil(o.DomainNames) {
		return true
	}

	return false
}

// SetDomainNames gets a reference to the given []string and assigns it to the DomainNames field.
func (o *PutProxyHostUpdateRequest) SetDomainNames(v []string) {
	o.DomainNames = v
}

// GetForwardScheme returns the ForwardScheme field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetForwardScheme() string {
	if o == nil || IsNil(o.ForwardScheme) {
		var ret string
		return ret
	}
	return *o.ForwardScheme
}

// GetForwardSchemeOk returns a tuple with the ForwardScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetForwardSchemeOk() (*string, bool) {
	if o == nil || IsNil(o.ForwardScheme) {
		return nil, false
	}
	return o.ForwardScheme, true
}

// HasForwardScheme returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasForwardScheme() bool {
	if o != nil && !IsNil(o.ForwardScheme) {
		return true
	}

	return false
}

// SetForwardScheme gets a reference to the given string and assigns it to the ForwardScheme field.
func (o *PutProxyHostUpdateRequest) SetForwardScheme(v string) {
	o.ForwardScheme = &v
}

// GetForwardHost returns the ForwardHost field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetForwardHost() string {
	if o == nil || IsNil(o.ForwardHost) {
		var ret string
		return ret
	}
	return *o.ForwardHost
}

// GetForwardHostOk returns a tuple with the ForwardHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetForwardHostOk() (*string, bool) {
	if o == nil || IsNil(o.ForwardHost) {
		return nil, false
	}
	return o.ForwardHost, true
}

// HasForwardHost returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasForwardHost() bool {
	if o != nil && !IsNil(o.ForwardHost) {
		return true
	}

	return false
}

// SetForwardHost gets a reference to the given string and assigns it to the ForwardHost field.
func (o *PutProxyHostUpdateRequest) SetForwardHost(v string) {
	o.ForwardHost = &v
}

// GetForwardPort returns the ForwardPort field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetForwardPort() int64 {
	if o == nil || IsNil(o.ForwardPort) {
		var ret int64
		return ret
	}
	return *o.ForwardPort
}

// GetForwardPortOk returns a tuple with the ForwardPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetForwardPortOk() (*int64, bool) {
	if o == nil || IsNil(o.ForwardPort) {
		return nil, false
	}
	return o.ForwardPort, true
}

// HasForwardPort returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasForwardPort() bool {
	if o != nil && !IsNil(o.ForwardPort) {
		return true
	}

	return false
}

// SetForwardPort gets a reference to the given int64 and assigns it to the ForwardPort field.
func (o *PutProxyHostUpdateRequest) SetForwardPort(v int64) {
	o.ForwardPort = &v
}

// GetCertificateId returns the CertificateId field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetCertificateId() PutProxyHostUpdateRequestCertificateId {
	if o == nil || IsNil(o.CertificateId) {
		var ret PutProxyHostUpdateRequestCertificateId
		return ret
	}
	return *o.CertificateId
}

// GetCertificateIdOk returns a tuple with the CertificateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetCertificateIdOk() (*PutProxyHostUpdateRequestCertificateId, bool) {
	if o == nil || IsNil(o.CertificateId) {
		return nil, false
	}
	return o.CertificateId, true
}

// HasCertificateId returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasCertificateId() bool {
	if o != nil && !IsNil(o.CertificateId) {
		return true
	}

	return false
}

// SetCertificateId gets a reference to the given PutProxyHostUpdateRequestCertificateId and assigns it to the CertificateId field.
func (o *PutProxyHostUpdateRequest) SetCertificateId(v PutProxyHostUpdateRequestCertificateId) {
	o.CertificateId = &v
}

// GetSslForced returns the SslForced field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetSslForced() boolAsInt {
	if o == nil || IsNil(o.SslForced) {
		var ret boolAsInt
		return ret
	}
	return *o.SslForced
}

// GetSslForcedOk returns a tuple with the SslForced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetSslForcedOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.SslForced) {
		return nil, false
	}
	return o.SslForced, true
}

// HasSslForced returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasSslForced() bool {
	if o != nil && !IsNil(o.SslForced) {
		return true
	}

	return false
}

// SetSslForced gets a reference to the given boolAsInt and assigns it to the SslForced field.
func (o *PutProxyHostUpdateRequest) SetSslForced(v boolAsInt) {
	o.SslForced = &v
}

// GetHstsEnabled returns the HstsEnabled field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetHstsEnabled() boolAsInt {
	if o == nil || IsNil(o.HstsEnabled) {
		var ret boolAsInt
		return ret
	}
	return *o.HstsEnabled
}

// GetHstsEnabledOk returns a tuple with the HstsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetHstsEnabledOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.HstsEnabled) {
		return nil, false
	}
	return o.HstsEnabled, true
}

// HasHstsEnabled returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasHstsEnabled() bool {
	if o != nil && !IsNil(o.HstsEnabled) {
		return true
	}

	return false
}

// SetHstsEnabled gets a reference to the given boolAsInt and assigns it to the HstsEnabled field.
func (o *PutProxyHostUpdateRequest) SetHstsEnabled(v boolAsInt) {
	o.HstsEnabled = &v
}

// GetHstsSubdomains returns the HstsSubdomains field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetHstsSubdomains() boolAsInt {
	if o == nil || IsNil(o.HstsSubdomains) {
		var ret boolAsInt
		return ret
	}
	return *o.HstsSubdomains
}

// GetHstsSubdomainsOk returns a tuple with the HstsSubdomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetHstsSubdomainsOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.HstsSubdomains) {
		return nil, false
	}
	return o.HstsSubdomains, true
}

// HasHstsSubdomains returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasHstsSubdomains() bool {
	if o != nil && !IsNil(o.HstsSubdomains) {
		return true
	}

	return false
}

// SetHstsSubdomains gets a reference to the given boolAsInt and assigns it to the HstsSubdomains field.
func (o *PutProxyHostUpdateRequest) SetHstsSubdomains(v boolAsInt) {
	o.HstsSubdomains = &v
}

// GetHttp2Support returns the Http2Support field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetHttp2Support() boolAsInt {
	if o == nil || IsNil(o.Http2Support) {
		var ret boolAsInt
		return ret
	}
	return *o.Http2Support
}

// GetHttp2SupportOk returns a tuple with the Http2Support field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetHttp2SupportOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.Http2Support) {
		return nil, false
	}
	return o.Http2Support, true
}

// HasHttp2Support returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasHttp2Support() bool {
	if o != nil && !IsNil(o.Http2Support) {
		return true
	}

	return false
}

// SetHttp2Support gets a reference to the given boolAsInt and assigns it to the Http2Support field.
func (o *PutProxyHostUpdateRequest) SetHttp2Support(v boolAsInt) {
	o.Http2Support = &v
}

// GetBlockExploits returns the BlockExploits field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetBlockExploits() boolAsInt {
	if o == nil || IsNil(o.BlockExploits) {
		var ret boolAsInt
		return ret
	}
	return *o.BlockExploits
}

// GetBlockExploitsOk returns a tuple with the BlockExploits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetBlockExploitsOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.BlockExploits) {
		return nil, false
	}
	return o.BlockExploits, true
}

// HasBlockExploits returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasBlockExploits() bool {
	if o != nil && !IsNil(o.BlockExploits) {
		return true
	}

	return false
}

// SetBlockExploits gets a reference to the given boolAsInt and assigns it to the BlockExploits field.
func (o *PutProxyHostUpdateRequest) SetBlockExploits(v boolAsInt) {
	o.BlockExploits = &v
}

// GetCachingEnabled returns the CachingEnabled field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetCachingEnabled() boolAsInt {
	if o == nil || IsNil(o.CachingEnabled) {
		var ret boolAsInt
		return ret
	}
	return *o.CachingEnabled
}

// GetCachingEnabledOk returns a tuple with the CachingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetCachingEnabledOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.CachingEnabled) {
		return nil, false
	}
	return o.CachingEnabled, true
}

// HasCachingEnabled returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasCachingEnabled() bool {
	if o != nil && !IsNil(o.CachingEnabled) {
		return true
	}

	return false
}

// SetCachingEnabled gets a reference to the given boolAsInt and assigns it to the CachingEnabled field.
func (o *PutProxyHostUpdateRequest) SetCachingEnabled(v boolAsInt) {
	o.CachingEnabled = &v
}

// GetAllowWebsocketUpgrade returns the AllowWebsocketUpgrade field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetAllowWebsocketUpgrade() boolAsInt {
	if o == nil || IsNil(o.AllowWebsocketUpgrade) {
		var ret boolAsInt
		return ret
	}
	return *o.AllowWebsocketUpgrade
}

// GetAllowWebsocketUpgradeOk returns a tuple with the AllowWebsocketUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetAllowWebsocketUpgradeOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.AllowWebsocketUpgrade) {
		return nil, false
	}
	return o.AllowWebsocketUpgrade, true
}

// HasAllowWebsocketUpgrade returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasAllowWebsocketUpgrade() bool {
	if o != nil && !IsNil(o.AllowWebsocketUpgrade) {
		return true
	}

	return false
}

// SetAllowWebsocketUpgrade gets a reference to the given boolAsInt and assigns it to the AllowWebsocketUpgrade field.
func (o *PutProxyHostUpdateRequest) SetAllowWebsocketUpgrade(v boolAsInt) {
	o.AllowWebsocketUpgrade = &v
}

// GetAccessListId returns the AccessListId field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetAccessListId() int64 {
	if o == nil || IsNil(o.AccessListId) {
		var ret int64
		return ret
	}
	return *o.AccessListId
}

// GetAccessListIdOk returns a tuple with the AccessListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetAccessListIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AccessListId) {
		return nil, false
	}
	return o.AccessListId, true
}

// HasAccessListId returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasAccessListId() bool {
	if o != nil && !IsNil(o.AccessListId) {
		return true
	}

	return false
}

// SetAccessListId gets a reference to the given int64 and assigns it to the AccessListId field.
func (o *PutProxyHostUpdateRequest) SetAccessListId(v int64) {
	o.AccessListId = &v
}

// GetAdvancedConfig returns the AdvancedConfig field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetAdvancedConfig() string {
	if o == nil || IsNil(o.AdvancedConfig) {
		var ret string
		return ret
	}
	return *o.AdvancedConfig
}

// GetAdvancedConfigOk returns a tuple with the AdvancedConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetAdvancedConfigOk() (*string, bool) {
	if o == nil || IsNil(o.AdvancedConfig) {
		return nil, false
	}
	return o.AdvancedConfig, true
}

// HasAdvancedConfig returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasAdvancedConfig() bool {
	if o != nil && !IsNil(o.AdvancedConfig) {
		return true
	}

	return false
}

// SetAdvancedConfig gets a reference to the given string and assigns it to the AdvancedConfig field.
func (o *PutProxyHostUpdateRequest) SetAdvancedConfig(v string) {
	o.AdvancedConfig = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetEnabled() boolAsInt {
	if o == nil || IsNil(o.Enabled) {
		var ret boolAsInt
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetEnabledOk() (*boolAsInt, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given boolAsInt and assigns it to the Enabled field.
func (o *PutProxyHostUpdateRequest) SetEnabled(v boolAsInt) {
	o.Enabled = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetMeta() map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *PutProxyHostUpdateRequest) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *PutProxyHostUpdateRequest) GetLocations() []PutProxyHostUpdateRequestLocationsInner {
	if o == nil || IsNil(o.Locations) {
		var ret []PutProxyHostUpdateRequestLocationsInner
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutProxyHostUpdateRequest) GetLocationsOk() ([]PutProxyHostUpdateRequestLocationsInner, bool) {
	if o == nil || IsNil(o.Locations) {
		return nil, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *PutProxyHostUpdateRequest) HasLocations() bool {
	if o != nil && !IsNil(o.Locations) {
		return true
	}

	return false
}

// SetLocations gets a reference to the given []PutProxyHostUpdateRequestLocationsInner and assigns it to the Locations field.
func (o *PutProxyHostUpdateRequest) SetLocations(v []PutProxyHostUpdateRequestLocationsInner) {
	o.Locations = v
}

func (o PutProxyHostUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutProxyHostUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainNames) {
		toSerialize["domain_names"] = o.DomainNames
	}
	if !IsNil(o.ForwardScheme) {
		toSerialize["forward_scheme"] = o.ForwardScheme
	}
	if !IsNil(o.ForwardHost) {
		toSerialize["forward_host"] = o.ForwardHost
	}
	if !IsNil(o.ForwardPort) {
		toSerialize["forward_port"] = o.ForwardPort
	}
	if !IsNil(o.CertificateId) {
		toSerialize["certificate_id"] = o.CertificateId
	}
	if !IsNil(o.SslForced) {
		toSerialize["ssl_forced"] = o.SslForced
	}
	if !IsNil(o.HstsEnabled) {
		toSerialize["hsts_enabled"] = o.HstsEnabled
	}
	if !IsNil(o.HstsSubdomains) {
		toSerialize["hsts_subdomains"] = o.HstsSubdomains
	}
	if !IsNil(o.Http2Support) {
		toSerialize["http2_support"] = o.Http2Support
	}
	if !IsNil(o.BlockExploits) {
		toSerialize["block_exploits"] = o.BlockExploits
	}
	if !IsNil(o.CachingEnabled) {
		toSerialize["caching_enabled"] = o.CachingEnabled
	}
	if !IsNil(o.AllowWebsocketUpgrade) {
		toSerialize["allow_websocket_upgrade"] = o.AllowWebsocketUpgrade
	}
	if !IsNil(o.AccessListId) {
		toSerialize["access_list_id"] = o.AccessListId
	}
	if !IsNil(o.AdvancedConfig) {
		toSerialize["advanced_config"] = o.AdvancedConfig
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Locations) {
		toSerialize["locations"] = o.Locations
	}
	return toSerialize, nil
}

type NullablePutProxyHostUpdateRequest struct {
	value *PutProxyHostUpdateRequest
	isSet bool
}

func (v NullablePutProxyHostUpdateRequest) Get() *PutProxyHostUpdateRequest {
	return v.value
}

func (v *NullablePutProxyHostUpdateRequest) Set(val *PutProxyHostUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutProxyHostUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutProxyHostUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutProxyHostUpdateRequest(val *PutProxyHostUpdateRequest) *NullablePutProxyHostUpdateRequest {
	return &NullablePutProxyHostUpdateRequest{value: val, isSet: true}
}

func (v NullablePutProxyHostUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutProxyHostUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


