/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.13.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the GetStreams200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStreams200ResponseInner{}

// GetStreams200ResponseInner Stream object
type GetStreams200ResponseInner struct {
	// Unique identifier
	Id int64 `json:"id"`
	// Date and time of creation
	CreatedOn string `json:"created_on"`
	// Date and time of last update
	ModifiedOn string `json:"modified_on"`
	// User ID
	OwnerUserId int64 `json:"owner_user_id"`
	IncomingPort int64 `json:"incoming_port"`
	ForwardingHost GetStreams200ResponseInnerForwardingHost `json:"forwarding_host"`
	ForwardingPort int64 `json:"forwarding_port"`
	TcpForwarding bool `json:"tcp_forwarding"`
	UdpForwarding bool `json:"udp_forwarding"`
	// Is Enabled
	Enabled bool `json:"enabled"`
	CertificateId *GetProxyHosts200ResponseInnerCertificateId `json:"certificate_id,omitempty"`
	Meta map[string]interface{} `json:"meta"`
	Certificate *GetRedirectionHosts200ResponseInnerCertificate `json:"certificate,omitempty"`
	Owner *GetAuditLogs200ResponseInnerUser `json:"owner,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetStreams200ResponseInner GetStreams200ResponseInner

// NewGetStreams200ResponseInner instantiates a new GetStreams200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStreams200ResponseInner(id int64, createdOn string, modifiedOn string, ownerUserId int64, incomingPort int64, forwardingHost GetStreams200ResponseInnerForwardingHost, forwardingPort int64, tcpForwarding bool, udpForwarding bool, enabled bool, meta map[string]interface{}) *GetStreams200ResponseInner {
	this := GetStreams200ResponseInner{}
	this.Id = id
	this.CreatedOn = createdOn
	this.ModifiedOn = modifiedOn
	this.OwnerUserId = ownerUserId
	this.IncomingPort = incomingPort
	this.ForwardingHost = forwardingHost
	this.ForwardingPort = forwardingPort
	this.TcpForwarding = tcpForwarding
	this.UdpForwarding = udpForwarding
	this.Enabled = enabled
	this.Meta = meta
	return &this
}

// NewGetStreams200ResponseInnerWithDefaults instantiates a new GetStreams200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStreams200ResponseInnerWithDefaults() *GetStreams200ResponseInner {
	this := GetStreams200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetStreams200ResponseInner) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetStreams200ResponseInner) SetId(v int64) {
	o.Id = v
}

// GetCreatedOn returns the CreatedOn field value
func (o *GetStreams200ResponseInner) GetCreatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetCreatedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedOn, true
}

// SetCreatedOn sets field value
func (o *GetStreams200ResponseInner) SetCreatedOn(v string) {
	o.CreatedOn = v
}

// GetModifiedOn returns the ModifiedOn field value
func (o *GetStreams200ResponseInner) GetModifiedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedOn
}

// GetModifiedOnOk returns a tuple with the ModifiedOn field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetModifiedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedOn, true
}

// SetModifiedOn sets field value
func (o *GetStreams200ResponseInner) SetModifiedOn(v string) {
	o.ModifiedOn = v
}

// GetOwnerUserId returns the OwnerUserId field value
func (o *GetStreams200ResponseInner) GetOwnerUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetOwnerUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerUserId, true
}

// SetOwnerUserId sets field value
func (o *GetStreams200ResponseInner) SetOwnerUserId(v int64) {
	o.OwnerUserId = v
}

// GetIncomingPort returns the IncomingPort field value
func (o *GetStreams200ResponseInner) GetIncomingPort() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IncomingPort
}

// GetIncomingPortOk returns a tuple with the IncomingPort field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetIncomingPortOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncomingPort, true
}

// SetIncomingPort sets field value
func (o *GetStreams200ResponseInner) SetIncomingPort(v int64) {
	o.IncomingPort = v
}

// GetForwardingHost returns the ForwardingHost field value
func (o *GetStreams200ResponseInner) GetForwardingHost() GetStreams200ResponseInnerForwardingHost {
	if o == nil {
		var ret GetStreams200ResponseInnerForwardingHost
		return ret
	}

	return o.ForwardingHost
}

// GetForwardingHostOk returns a tuple with the ForwardingHost field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetForwardingHostOk() (*GetStreams200ResponseInnerForwardingHost, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForwardingHost, true
}

// SetForwardingHost sets field value
func (o *GetStreams200ResponseInner) SetForwardingHost(v GetStreams200ResponseInnerForwardingHost) {
	o.ForwardingHost = v
}

// GetForwardingPort returns the ForwardingPort field value
func (o *GetStreams200ResponseInner) GetForwardingPort() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ForwardingPort
}

// GetForwardingPortOk returns a tuple with the ForwardingPort field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetForwardingPortOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForwardingPort, true
}

// SetForwardingPort sets field value
func (o *GetStreams200ResponseInner) SetForwardingPort(v int64) {
	o.ForwardingPort = v
}

// GetTcpForwarding returns the TcpForwarding field value
func (o *GetStreams200ResponseInner) GetTcpForwarding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TcpForwarding
}

// GetTcpForwardingOk returns a tuple with the TcpForwarding field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetTcpForwardingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TcpForwarding, true
}

// SetTcpForwarding sets field value
func (o *GetStreams200ResponseInner) SetTcpForwarding(v bool) {
	o.TcpForwarding = v
}

// GetUdpForwarding returns the UdpForwarding field value
func (o *GetStreams200ResponseInner) GetUdpForwarding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UdpForwarding
}

// GetUdpForwardingOk returns a tuple with the UdpForwarding field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetUdpForwardingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UdpForwarding, true
}

// SetUdpForwarding sets field value
func (o *GetStreams200ResponseInner) SetUdpForwarding(v bool) {
	o.UdpForwarding = v
}

// GetEnabled returns the Enabled field value
func (o *GetStreams200ResponseInner) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *GetStreams200ResponseInner) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCertificateId returns the CertificateId field value if set, zero value otherwise.
func (o *GetStreams200ResponseInner) GetCertificateId() GetProxyHosts200ResponseInnerCertificateId {
	if o == nil || IsNil(o.CertificateId) {
		var ret GetProxyHosts200ResponseInnerCertificateId
		return ret
	}
	return *o.CertificateId
}

// GetCertificateIdOk returns a tuple with the CertificateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetCertificateIdOk() (*GetProxyHosts200ResponseInnerCertificateId, bool) {
	if o == nil || IsNil(o.CertificateId) {
		return nil, false
	}
	return o.CertificateId, true
}

// HasCertificateId returns a boolean if a field has been set.
func (o *GetStreams200ResponseInner) HasCertificateId() bool {
	if o != nil && !IsNil(o.CertificateId) {
		return true
	}

	return false
}

// SetCertificateId gets a reference to the given GetProxyHosts200ResponseInnerCertificateId and assigns it to the CertificateId field.
func (o *GetStreams200ResponseInner) SetCertificateId(v GetProxyHosts200ResponseInnerCertificateId) {
	o.CertificateId = &v
}

// GetMeta returns the Meta field value
func (o *GetStreams200ResponseInner) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetStreams200ResponseInner) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *GetStreams200ResponseInner) GetCertificate() GetRedirectionHosts200ResponseInnerCertificate {
	if o == nil || IsNil(o.Certificate) {
		var ret GetRedirectionHosts200ResponseInnerCertificate
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetCertificateOk() (*GetRedirectionHosts200ResponseInnerCertificate, bool) {
	if o == nil || IsNil(o.Certificate) {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *GetStreams200ResponseInner) HasCertificate() bool {
	if o != nil && !IsNil(o.Certificate) {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given GetRedirectionHosts200ResponseInnerCertificate and assigns it to the Certificate field.
func (o *GetStreams200ResponseInner) SetCertificate(v GetRedirectionHosts200ResponseInnerCertificate) {
	o.Certificate = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *GetStreams200ResponseInner) GetOwner() GetAuditLogs200ResponseInnerUser {
	if o == nil || IsNil(o.Owner) {
		var ret GetAuditLogs200ResponseInnerUser
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStreams200ResponseInner) GetOwnerOk() (*GetAuditLogs200ResponseInnerUser, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *GetStreams200ResponseInner) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given GetAuditLogs200ResponseInnerUser and assigns it to the Owner field.
func (o *GetStreams200ResponseInner) SetOwner(v GetAuditLogs200ResponseInnerUser) {
	o.Owner = &v
}

func (o GetStreams200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStreams200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_on"] = o.CreatedOn
	toSerialize["modified_on"] = o.ModifiedOn
	toSerialize["owner_user_id"] = o.OwnerUserId
	toSerialize["incoming_port"] = o.IncomingPort
	toSerialize["forwarding_host"] = o.ForwardingHost
	toSerialize["forwarding_port"] = o.ForwardingPort
	toSerialize["tcp_forwarding"] = o.TcpForwarding
	toSerialize["udp_forwarding"] = o.UdpForwarding
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.CertificateId) {
		toSerialize["certificate_id"] = o.CertificateId
	}
	toSerialize["meta"] = o.Meta
	if !IsNil(o.Certificate) {
		toSerialize["certificate"] = o.Certificate
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetStreams200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_on",
		"modified_on",
		"owner_user_id",
		"incoming_port",
		"forwarding_host",
		"forwarding_port",
		"tcp_forwarding",
		"udp_forwarding",
		"enabled",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetStreams200ResponseInner := _GetStreams200ResponseInner{}

	err = json.Unmarshal(data, &varGetStreams200ResponseInner)

	if err != nil {
		return err
	}

	*o = GetStreams200ResponseInner(varGetStreams200ResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_on")
		delete(additionalProperties, "modified_on")
		delete(additionalProperties, "owner_user_id")
		delete(additionalProperties, "incoming_port")
		delete(additionalProperties, "forwarding_host")
		delete(additionalProperties, "forwarding_port")
		delete(additionalProperties, "tcp_forwarding")
		delete(additionalProperties, "udp_forwarding")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "certificate_id")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "certificate")
		delete(additionalProperties, "owner")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetStreams200ResponseInner struct {
	value *GetStreams200ResponseInner
	isSet bool
}

func (v NullableGetStreams200ResponseInner) Get() *GetStreams200ResponseInner {
	return v.value
}

func (v *NullableGetStreams200ResponseInner) Set(val *GetStreams200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStreams200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStreams200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStreams200ResponseInner(val *GetStreams200ResponseInner) *NullableGetStreams200ResponseInner {
	return &NullableGetStreams200ResponseInner{value: val, isSet: true}
}

func (v NullableGetStreams200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStreams200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


