/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.13.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateAccessListRequestClientsInnerAddress - struct for CreateAccessListRequestClientsInnerAddress
type CreateAccessListRequestClientsInnerAddress struct {
	String *string
}

// stringAsCreateAccessListRequestClientsInnerAddress is a convenience function that returns string wrapped in CreateAccessListRequestClientsInnerAddress
func StringAsCreateAccessListRequestClientsInnerAddress(v *string) CreateAccessListRequestClientsInnerAddress {
	return CreateAccessListRequestClientsInnerAddress{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateAccessListRequestClientsInnerAddress) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateAccessListRequestClientsInnerAddress)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateAccessListRequestClientsInnerAddress)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateAccessListRequestClientsInnerAddress) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateAccessListRequestClientsInnerAddress) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateAccessListRequestClientsInnerAddress) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCreateAccessListRequestClientsInnerAddress struct {
	value *CreateAccessListRequestClientsInnerAddress
	isSet bool
}

func (v NullableCreateAccessListRequestClientsInnerAddress) Get() *CreateAccessListRequestClientsInnerAddress {
	return v.value
}

func (v *NullableCreateAccessListRequestClientsInnerAddress) Set(val *CreateAccessListRequestClientsInnerAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessListRequestClientsInnerAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessListRequestClientsInnerAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessListRequestClientsInnerAddress(val *CreateAccessListRequestClientsInnerAddress) *NullableCreateAccessListRequestClientsInnerAddress {
	return &NullableCreateAccessListRequestClientsInnerAddress{value: val, isSet: true}
}

func (v NullableCreateAccessListRequestClientsInnerAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessListRequestClientsInnerAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


